# Generated by Django 5.0.1 on 2024-02-10 15:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('cid', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('client_Name', models.CharField(max_length=40, null=True)),
                ('business_Name', models.CharField(max_length=40, null=True)),
                ('email', models.EmailField(max_length=40, null=True)),
                ('contact', models.CharField(max_length=12, null=True)),
                ('pan_Card', models.CharField(max_length=10, null=True)),
                ('pan_Image', models.ImageField(upload_to='Pictures')),
                ('aadhar_Card', models.CharField(max_length=12, null=True)),
                ('adhar_Image', models.ImageField(upload_to='Pictures')),
                ('address', models.CharField(max_length=40, null=True)),
                ('assign_Person', models.CharField(max_length=40, null=True)),
                ('industies_Type', models.CharField(choices=[('EV', 'EV'), ('Portable', 'Portable'), ('Industrial', 'Industrial')], max_length=20, null=True)),
                ('account_Type', models.CharField(choices=[('Regular', 'Regular'), ('Contract', 'Contract')], max_length=20, null=True)),
                ('status', models.CharField(choices=[('Onboarding', 'Onboarding'), ('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=40, null=True)),
                ('types_of_Battery', models.CharField(choices=[('Two Wheeler', 'Two Wheeler'), ('Three Wheeler', 'Three Wheeler'), ('Four Wheeler', 'Four Wheeler'), ('Portable', 'Portable')], max_length=100, null=True)),
                ('cell_Chemistry', models.CharField(choices=[('NMC', 'NMC'), ('LFP', 'LFP'), ('LCO', 'LCO')], max_length=100, null=True)),
                ('Industry_Type', models.CharField(choices=[('EV', 'EV'), ('Portable', 'Portable'), ('Industrial', 'Industrial')], max_length=20, null=True)),
                ('UOM', models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Unit', 'Unit')], max_length=10, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('HSN_Code', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=40)),
                ('user_pic', models.ImageField(null=True, upload_to='user_pic')),
                ('user_Type', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], max_length=40, null=True)),
                ('department', models.CharField(choices=[('Finance', 'Finance'), ('Operation', 'Operation'), ('Associate', 'Associate'), ('IT', 'IT'), ('HR', 'HR')], max_length=40, null=True)),
                ('location', models.CharField(choices=[('Gurgoan', 'Gurgoan'), ('Noida', 'Noida')], max_length=40, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(choices=[('BatX', 'BatX'), ('Client', 'Client'), ('Vinay', 'Vinay')], max_length=100, null=True)),
                ('rfqorder', models.CharField(max_length=100, null=True)),
                ('rfqid', models.CharField(max_length=10, unique=True)),
                ('order_quantity', models.PositiveIntegerField(null=True)),
                ('valid', models.DateTimeField(max_length=100, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('unit', models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Unit', 'Unit')], max_length=10, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
