# Generated by Django 5.0.1 on 2024-02-12 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_rename_total_crfq_subtotal_remove_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crfq',
            old_name='unit',
            new_name='uom',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='rfqorder',
        ),
        migrations.AddField(
            model_name='crfq',
            name='Packaging',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crfq',
            name='payment',
            field=models.CharField(choices=[('Advance', 'Advance'), ('Upon Dispatch', 'Upon Dispatch'), ('Balance', 'Balance')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='crfq',
            name='total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='crfq',
            name='transportation',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='crfq',
            name='notes',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AlterField(
            model_name='crfq',
            name='tcs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
