# Generated by Django 5.0.1 on 2024-02-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_rename_unit_crfq_uom_remove_crfq_rfqorder_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crfq',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='taxamt',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='taxval',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='tcs',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='tcsval',
        ),
    ]
