# Generated by Django 5.0.1 on 2024-02-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_crfq_subtotal_remove_crfq_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crfq',
            name='total',
        ),
    ]
