# Generated by Django 5.0.1 on 2024-02-15 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_remove_crfq_desc_remove_crfq_order_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='rfqid',
            field=models.ForeignKey(default=1, max_length=10, on_delete=django.db.models.deletion.CASCADE, to='inventory.crfq', unique=True),
            preserve_default=False,
        ),
    ]
