# Generated by Django 5.0.1 on 2024-02-15 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_crfq_desc_crfq_order_quantity_crfq_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crfq',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='order_quantity',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='price',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='product',
        ),
        migrations.RemoveField(
            model_name='crfq',
            name='uom',
        ),
        migrations.CreateModel(
            name='Rfq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('order_quantity', models.PositiveIntegerField()),
                ('uom', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crfq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.crfq')),
            ],
        ),
    ]
