# Generated by Django 5.0.1 on 2024-02-15 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_crfq_desc_remove_crfq_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
