# Generated by Django 5.0.1 on 2024-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_alter_rfq_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfq',
            name='uom',
            field=models.CharField(choices=[('KG', 'KG'), ('Gram', 'Gram'), ('Unit', 'Unit')], max_length=10),
        ),
    ]
